dist: xenial
language: python
python:
- 3.5
- 3.6
- 3.7
- 3.8
- pypy3
install:
- pip install -U tox-travis
- pip install -e .[dev]
- python setup.py develop
addons:
  apt:
    sources:
    - sourceline: ppa:jonathonf/ffmpeg-4
    packages:
    - pkg-config
    - libavcodec-dev
    - libavformat-dev
    - libavutil-dev
    - libavdevice-dev
    - libavfilter-dev
    - libswscale-dev
    - libswresample-dev
    - ffmpeg
    - libsdl2-dev
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: "__token__"
  password:
    secure: "na/wyeOxIPodl2p73SuwHloqQg7DHh46PcoASzy4i31kscSZn3LdWxTZyDcRxojStcw9K7XmviiZ8UVpBmcHMQVX6H07s4nKyjEuUdEUhiH6+OfH0w3jSa5OY2ZPA7h7hmbYmBYf9IxHR1FBgXP/fGwcLaPTewXMv5Owh8epIC7v8RC1ZK2nsbzudTIY1i7fmjlMuHB17mIcpmp+1bakHWD9T56pK+7K9yP4akjr48hK7MVlB4BK3PygluMKj33wV6yEh2nl2ohNpVatmluO3Ap2S5G9aiU2nj83Q4SVsRj/zwYGjo5Tn9yqfie75R6I8AxaW7sosDXiONuotlZl/1sKrT3CjeLQBPvU1qs97dKktmEDd70aEziRyrB9MqKBMTO/G9itAXhJsdfOdpQu/V0ToaeYAUkSH71lyKzm8+I0G3Qe9Kes8+1bxZTBVdQim0cjPwSpDf7PgSWlcgLvFmJckzw7fXkwMH7AnIK8iLrcHNr45y4dD6g3jE2HgTPbLz954QQDLOYI6lrs7Z7f10vkzLoumDC+oplZvj54D+5uA3pkLxO+kDZFYkMkOsDdmHdFUoo48FZzOhRu7z8fv3dPFnXAWRdoAbS4db3YdE2fZLq+n+hFmpyb2qhLijOc39oMBQFbbWiaGF72Alox1avvQYkh69BXUysl4xvS6T8="
  on:
    tags: true
    branch: master
    python: 3.6
